apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    openshift.io/display-name: vLLM
    opendatahub.io/accelerator-name: ""
    opendatahub.io/apiProtocol: REST
    opendatahub.io/template-name: vLLM
  name: vllm
spec:
  builtInAdapter:
    modelLoadingTimeoutMillis: 90000
  containers:
    - name: kserve-container
      args:
        - --model
        - /mnt/models/
        - --download-dir
        - /models-cache
        - --port
        - "8080"
        - --max-model-len
        - "2048"
      image: quay.io/rh-aiservices-bu/vllm-openai-ubi9:0.4.2
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: pytorch
