apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-config
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'openshift-gitops'
      server: '*'
  sourceRepos:
    - '*'
