kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio
spec:
  template:
    spec:
      containers:
        - name: minio
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 20m
              memory: 100Mi
