apiVersion: batch/v1
kind: Job
metadata:
  name: create-buckets
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: create-buckets
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2023.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
          envFrom:
            - secretRef:
                name: aws-connection-example
          args:
            - -ec
            - |-
              env | grep AWS_
              python3 /scripts/create-bucket.py
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: create-bucket
      restartPolicy: Never
