apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm1
spec:
  template:
    spec:
      containers:
        - name: server
          resources:
            limits:
              nvidia.com/gpu: "8"
              cpu: "60"
              memory: 190Gi
