apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm1
spec:
  template:
    spec:
      containers:
        - name: server
          args:
            - "--model"
            - mistralai/Mixtral-8x7B-Instruct-v0.1
            - "--dtype"
            - float16
            - "--tensor-parallel-size=8"
