---
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
  labels:
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/instance: default-dsc
    app.kubernetes.io/part-of: rhods-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rhods-operator
spec:
  components:
    codeflare:
      managementState: Removed
    kserve:
      serving:
        ingressGateway:
          certificate:
            type: SelfSigned
        managementState: Managed
        name: knative-serving
      managementState: Managed
    ray:
      managementState: Removed
    kueue:
      managementState: Removed
    workbenches:
      managementState: Managed
    dashboard:
      managementState: Managed
    modelmeshserving:
      managementState: Managed
    datasciencepipelines:
      managementState: Managed

# ---
# apiVersion: dscinitialization.opendatahub.io/v1
# kind: DSCInitialization
# metadata:
#   finalizers:
#     - dscinitialization.opendatahub.io/finalizer
#   name: default-dsci
# spec:
#   applicationsNamespace: redhat-ods-applications
#   monitoring:
#     managementState: Managed
#     namespace: redhat-ods-monitoring
#   serviceMesh:
#     controlPlane:
#       metricsCollection: Istio
#       name: data-science-smcp
#       namespace: istio-system
#     managementState: Managed
#   trustedCABundle:
#     customCABundle: ''
#     managementState: Managed
