apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-example-training

# nameSuffix: -test

labels:
- includeSelectors: false
  pairs:
    opendatahub.io/dashboard: "true"

resources:
  - example-workbench-pvc.yaml
  - example-workbench.yaml
