apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-example-multi-model-serving

resources:
  - ./setup-jobs
  - data-connection.yaml
  - inference-service.yaml
  - serving-runtime.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: patch-model-details.yaml
    target:
      kind: Job
      name: upload-model-to-s3-multi-model

replacements:
  - source:
      kind: Secret
      name: aws-connection-multi-model
      fieldPath: metadata.name
    targets:
      - select:
          kind: Job
          name: create-buckets-multi-model
        fieldPaths:
          - spec.template.spec.containers.0.envFrom.0.secretRef.name
      - select:
          kind: Job
          name: upload-model-to-s3-multi-model
        fieldPaths:
          - spec.template.spec.containers.0.envFrom.0.secretRef.name
