kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-tgis
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: tgis
    argocd.argoproj.io/sync-wave: "-100"
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_S3_BUCKET: tgis
  AWS_S3_ENDPOINT: http://minio.ai-example-single-model-serving.svc.cluster.local:9000
  AWS_SECRET_ACCESS_KEY: minio123
type: Opaque
