apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/accelerator-name: ""
    opendatahub.io/apiProtocol: gRPC
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: TGIS Standalone ServingRuntime for KServe
    opendatahub.io/template-name: tgis-grpc-runtime
    openshift.io/display-name: tgis
  labels:
    opendatahub.io/dashboard: "true"
  name: tgis
spec:
  containers:
  - name: kserve-container
    image: quay.io/modh/text-generation-inference@sha256:18048121be7624d8cfe3f387e6de7ebb2e9376213f795d66cada26d8391229ca
    command:
      - text-generation-launcher
    args:
      - --model-name=/mnt/models/
      - --port=3000
      - --grpc-port=8033
    env:
      - name: TRANSFORMERS_CACHE
        value: /tmp/transformers_cache
    livenessProbe:
      exec:
        command:
          - curl
          - localhost:3000/health
      initialDelaySeconds: 5
    readinessProbe:
      exec:
        command:
        - curl
        - localhost:3000/health
      initialDelaySeconds: 5
    ports:
      - containerPort: 8033
        name: h2c
        protocol: TCP
    resources:
      limits:
        cpu: "2"
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 4Gi
    volumeMounts:
      - mountPath: /dev/shm
        name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: pytorch
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
