apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm1
spec:
  template:
    spec:
      containers:
        - name: server
          args:
            - "--model"
            - meta-llama/Llama-2-13b-chat-hf
            - "--dtype"
            - float16
            - "--tensor-parallel-size=2"
